# Generated by Django 6.0.3 on 2026-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
