# Generated by Django 6.0.3 on 2026-04-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitter_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitter',
            old_name='price_per_night',
            new_name='price',
        ),
    ]
